mod common;

#[cfg(unix)]
mod unix_only {
    use super::common::{ensure_success, setup_hotfix_repo};
    use anyhow::Result;
    use std::env;
    use std::fs;
    use std::os::unix::fs::PermissionsExt;
    use std::path::Path;
    use std::process::Command;
    use why_archaeologist::analyze_target_with_options;
    use why_locator::parse_target;

    fn set_executable(path: &Path) -> Result<()> {
        let mut permissions = fs::metadata(path)?.permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(path, permissions)?;
        Ok(())
    }

    #[test]
    fn pre_commit_hook_runs_why_against_a_full_file_range() -> Result<()> {
        let repo = setup_hotfix_repo()?;
        why_hooks::installer::install(&repo.path, true)?;

        let hook_path = repo.path.join(".git/hooks/pre-commit");
        let hook_script = fs::read_to_string(&hook_path)?;
        assert!(hook_script.contains("why \"$file\" --lines \"1:${line_count}\" --no-llm --json"));

        let source_path = repo.path.join("src/payment.rs");
        let updated_source = format!(
            "{}\n// touched by integration test\n",
            fs::read_to_string(&source_path)?
        );
        fs::write(&source_path, updated_source)?;
        ensure_success(&repo.run_command("git", &["add", "src/payment.rs"])?)?;

        let stub_bin_dir = repo.path.join("test-bin");
        fs::create_dir_all(&stub_bin_dir)?;
        let args_log = repo.path.join("why-args.log");
        let stub_path = stub_bin_dir.join("why");
        fs::write(
            &stub_path,
            format!(
                "#!/usr/bin/env bash\nset -euo pipefail\nprintf '%s\\n' \"$@\" > \"{}\"\nprintf '{{\\\"risk_level\\\":\\\"HIGH\\\"}}\\n'\n",
                args_log.display()
            ),
        )?;
        set_executable(&stub_path)?;

        let output = Command::new(&hook_path)
            .current_dir(&repo.path)
            .env(
                "PATH",
                format!(
                    "{}:{}",
                    stub_bin_dir.display(),
                    env::var("PATH").unwrap_or_default()
                ),
            )
            .output()?;

        assert!(
            output.status.success(),
            "hook failed\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );

        let logged_args = fs::read_to_string(&args_log)?;
        let args: Vec<_> = logged_args.lines().collect();
        assert_eq!(args[0], "src/payment.rs");
        assert_eq!(args[1], "--lines");
        assert!(args[2].starts_with("1:"));
        assert_eq!(args[3], "--no-llm");
        assert_eq!(args[4], "--json");
        assert!(String::from_utf8_lossy(&output.stdout).contains("--warn-only is enabled"));

        why_hooks::installer::uninstall(&repo.path)?;
        assert!(!hook_path.exists());
        Ok(())
    }

    #[test]
    fn annotator_writer_inserts_and_refreshes_history_block_end_to_end() -> Result<()> {
        let repo = setup_hotfix_repo()?;
        let target = parse_target("src/payment.rs:process_payment", None)?;
        let result = analyze_target_with_options(&target, &repo.path, None)?;
        let head = repo.run_command("git", &["rev-parse", "HEAD"])?;
        ensure_success(&head)?;
        let head_hash = String::from_utf8_lossy(&head.stdout).trim().to_string();
        let source_path = repo.path.join("src/payment.rs");

        why_annotator::writer::annotate_file(
            &source_path,
            result.target.start_line,
            &result,
            &head_hash,
            "src/payment.rs:process_payment",
        )?;

        let first = fs::read_to_string(&source_path)?;
        assert!(first.contains("/// [why]"));
        assert!(first.contains("Risk:"));
        assert!(first.contains("Evidence:"));
        assert!(first.contains("Refresh: `why src/payment.rs:process_payment --annotate`"));
        assert_eq!(first.matches("/// [why]").count(), 1);

        let refreshed = analyze_target_with_options(&target, &repo.path, None)?;
        why_annotator::writer::annotate_file(
            &source_path,
            refreshed.target.start_line,
            &refreshed,
            &head_hash,
            "src/payment.rs:process_payment",
        )?;

        let second = fs::read_to_string(&source_path)?;
        assert_eq!(second.matches("/// [why]").count(), 1);
        assert!(second.contains("Generated by `why` @"));
        assert!(second.contains("duplicate charge incident"));
        Ok(())
    }
}
