use anyhow::{Context, Result, bail};
use std::fs;
use std::path::Path;
use why_archaeologist::{ArchaeologyResult, CommitEvidence, RiskLevel};

const GENERATED_PREFIX: &str = "Generated by `why` @ ";

pub fn annotate_file(
    file_path: &Path,
    start_line: u32,
    result: &ArchaeologyResult,
    head_hash: &str,
    refresh_target: &str,
) -> Result<()> {
    if start_line == 0 {
        bail!("annotation start line must be 1-based");
    }

    let source = fs::read_to_string(file_path)
        .with_context(|| format!("failed to read source file {}", file_path.display()))?;
    let newline = detect_newline(&source);
    let mut lines: Vec<String> = source.lines().map(ToOwned::to_owned).collect();

    if source.ends_with('\n') && lines.is_empty() {
        lines.push(String::new());
    }

    let insert_index = usize::try_from(start_line - 1)
        .context("annotation start line could not be converted to an index")?;
    if insert_index > lines.len() {
        bail!(
            "annotation start line {} exceeds file length {}",
            start_line,
            lines.len()
        );
    }

    let annotation = render_annotation(result, head_hash, refresh_target);
    let block_start = find_existing_block_start(&lines, insert_index);
    let insertion_point = block_start.unwrap_or(insert_index);

    if let Some(start) = block_start {
        let end = find_existing_block_end(&lines, start);
        lines.drain(start..end);
    }

    for (offset, line) in annotation.into_iter().enumerate() {
        lines.insert(insertion_point + offset, line);
    }

    let mut updated = lines.join(newline);
    if source.ends_with('\n') || !updated.is_empty() {
        updated.push_str(newline);
    }

    fs::write(file_path, updated)
        .with_context(|| format!("failed to write annotation to {}", file_path.display()))
}

fn render_annotation(
    result: &ArchaeologyResult,
    head_hash: &str,
    refresh_target: &str,
) -> Vec<String> {
    let summary = build_summary(result);
    let evidence = build_evidence(result.commits.as_slice());
    let generated = format!(
        "/// {GENERATED_PREFIX}{}. Refresh: `why {} --annotate`",
        short_head_hash(head_hash),
        refresh_target
    );

    vec![wrap_doc_line(&summary), wrap_doc_line(&evidence), generated]
}

fn build_summary(result: &ArchaeologyResult) -> String {
    let lead = result
        .commits
        .iter()
        .find(|commit| !commit.is_mechanical)
        .or_else(|| result.commits.first());

    let rationale = lead
        .map(commit_rationale)
        .filter(|text| !text.is_empty())
        .unwrap_or_else(|| "Historical context preserved in git history.".to_string());

    format!(
        "[why] {} Risk: {}. Confidence: {}.",
        rationale,
        result.risk_level.as_str(),
        confidence_label(result.commits.as_slice(), result.risk_level)
    )
}

fn build_evidence(commits: &[CommitEvidence]) -> String {
    if commits.is_empty() {
        return "/// Evidence: no commit evidence found.".to_string();
    }

    let entries = commits
        .iter()
        .take(3)
        .map(|commit| {
            format!(
                "{} — {}",
                commit.short_oid,
                sanitize_fragment(&commit.summary)
            )
        })
        .collect::<Vec<_>>()
        .join("; ");

    format!("/// Evidence: {entries}.")
}

fn commit_rationale(commit: &CommitEvidence) -> String {
    let summary = sanitize_fragment(&commit.summary);
    if summary.is_empty() {
        return String::new();
    }

    format!(
        "{} (commit {}, {}).",
        summary, commit.short_oid, commit.date
    )
}

fn confidence_label(commits: &[CommitEvidence], risk_level: RiskLevel) -> &'static str {
    if commits.len() >= 3 {
        return "high";
    }

    if commits.len() == 2 {
        return if matches!(risk_level, RiskLevel::HIGH) {
            "medium-high"
        } else {
            "medium"
        };
    }

    if commits.len() == 1 {
        return if matches!(risk_level, RiskLevel::HIGH) {
            "medium"
        } else {
            "low"
        };
    }

    "low"
}

fn short_head_hash(head_hash: &str) -> &str {
    let end = head_hash.len().min(7);
    &head_hash[..end]
}

fn sanitize_fragment(value: &str) -> String {
    value
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
        .trim_end_matches('.')
        .to_string()
}

fn wrap_doc_line(content: &str) -> String {
    format!("/// {content}")
}

fn find_existing_block_start(lines: &[String], insert_index: usize) -> Option<usize> {
    let mut index = insert_index;
    while index > 0 {
        let previous = &lines[index - 1];
        if previous.starts_with("/// ") {
            if previous.starts_with("/// [why]") {
                return Some(index - 1);
            }
            index -= 1;
            continue;
        }
        break;
    }

    None
}

fn find_existing_block_end(lines: &[String], start: usize) -> usize {
    let mut index = start;
    while index < lines.len() {
        let line = &lines[index];
        if line.starts_with("/// ") {
            index += 1;
            continue;
        }
        break;
    }
    index
}

fn detect_newline(source: &str) -> &str {
    if source.contains("\r\n") {
        "\r\n"
    } else {
        "\n"
    }
}

#[cfg(test)]
mod tests {
    use super::annotate_file;
    use anyhow::Result;
    use std::fs;
    use tempfile::tempdir;
    use why_archaeologist::{ArchaeologyResult, CommitEvidence, OutputTarget, RiskLevel};
    use why_locator::QueryKind;

    #[test]
    fn inserts_annotation_before_target_line() -> Result<()> {
        let dir = tempdir()?;
        let file = dir.path().join("sample.rs");
        fs::write(&file, "pub fn authenticate() {}\n")?;

        annotate_file(
            &file,
            1,
            &sample_result(),
            "abcdef123456",
            "src/lib.rs:authenticate",
        )?;

        let updated = fs::read_to_string(&file)?;
        assert!(updated.contains("/// [why] fix: preserve auth token flow"));
        assert!(updated.contains("/// Evidence: abc1234 — fix: preserve auth token flow"));
        assert!(updated.contains("Refresh: `why src/lib.rs:authenticate --annotate`"));
        assert!(updated.ends_with("pub fn authenticate() {}\n"));
        Ok(())
    }

    #[test]
    fn rerun_replaces_existing_why_block_idempotently() -> Result<()> {
        let dir = tempdir()?;
        let file = dir.path().join("sample.rs");
        fs::write(
            &file,
            "/// [why] old context\n/// Evidence: old evidence.\n/// Generated by `why` @ old1234. Refresh: `why old --annotate`\npub fn authenticate() {}\n",
        )?;

        annotate_file(
            &file,
            4,
            &sample_result(),
            "fedcba987654",
            "src/lib.rs:authenticate",
        )?;

        let updated = fs::read_to_string(&file)?;
        assert_eq!(updated.matches("/// [why]").count(), 1);
        assert!(!updated.contains("old context"));
        assert!(updated.contains("Generated by `why` @ fedcba9"));
        Ok(())
    }

    #[test]
    fn preserves_unrelated_doc_comments_above_annotation_block() -> Result<()> {
        let dir = tempdir()?;
        let file = dir.path().join("sample.rs");
        fs::write(
            &file,
            "/// Existing docs\n/// More docs\npub fn authenticate() {}\n",
        )?;

        annotate_file(
            &file,
            3,
            &sample_result(),
            "abcdef123456",
            "src/lib.rs:authenticate",
        )?;

        let updated = fs::read_to_string(&file)?;
        assert!(updated.starts_with("/// Existing docs\n/// More docs\n/// [why]"));
        Ok(())
    }

    fn sample_result() -> ArchaeologyResult {
        ArchaeologyResult {
            target: OutputTarget {
                path: "src/lib.rs".into(),
                start_line: 1,
                end_line: 1,
                query_kind: QueryKind::Symbol,
            },
            commits: vec![CommitEvidence {
                oid: "abc1234def5678".into(),
                short_oid: "abc1234".into(),
                author: "Test Author".into(),
                email: "test@example.com".into(),
                time: 0,
                date: "2026-03-01".into(),
                summary: "fix: preserve auth token flow".into(),
                message: "fix: preserve auth token flow\n\nrefs #101".into(),
                diff_excerpt: "diff --git a/src/lib.rs b/src/lib.rs".into(),
                coverage_score: 1.0,
                relevance_score: 0.8,
                issue_refs: vec!["#101".into()],
                is_mechanical: false,
            }],
            risk_level: RiskLevel::HIGH,
            risk_summary: RiskLevel::HIGH.summary().to_string(),
            change_guidance: RiskLevel::HIGH.change_guidance().to_string(),
            local_context: why_archaeologist::LocalContext {
                comments: vec!["temporary auth safeguard".into()],
                markers: vec!["TODO: remove after rollout".into()],
                risk_flags: vec!["auth".into(), "token".into()],
            },
            mode: "heuristic".to_string(),
            notes: vec!["No LLM synthesis in phase 1".to_string()],
        }
    }
}
